package org.example;

/**
 * UC2: Render OOPS Banner using Print Statements
 *
 * This class demonstrates printing an OOPS banner to the console using
 * ASCII art style. Each line of the banner is printed using separate
 * System.out.println statements.
 * <p>Banner is generated by printing predefined string patterns line by line
 * to form the letters O, O, P, and S in a style that resembles a banner.
 * This example showcases basic console output in Java.
 * </p>



*@author Sumukha
*@version 1.0

 */

public class OOPSBannerApp {
    public static void main(String[] args) {
        System.out.println("OOPS");
    }
}
